### PR TITLE
Adding example to commit nightly to gh-pages

### LINKED ISSUE #17: Possible to commit directly?
The action currently creates a PR, would we be able make a variant that commits to master or gh-pages as well?

For context, this is what I do now using a DroneCI daily cron, to build the frontend and widgets.

### PR DESCRIPTION
**Pull request by vsoch**
This will add an example action that is scheduled to run nightly (or at some frequency) to update the graphic on some branch like GitHub pages. It is currently set to run at 2:30am, so the first test will be early tomorrow morning!

This will close #17 

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
@Beanow this should be good to go to test for a nightly push to gh-pages here - would you care to quickly review?

**Comment by Beanow** [comment]
Reading over it this looks good.
Also a safe approach to add new commits. Vs force pushing a single commit.

The data volume used, is that discarded every run? If so, for a larger repository it's probably worth looking into caching it.

**Comment by vsoch** [comment]
That's a good question - I'm not well practiced with caching with GitHub actions. If it's okay with you, we can open this as another issue, as it would make sense to add to both templates.

**Comment by Beanow** [comment]
Sounds good to me :]

**Comment by vsoch** [comment]
A-ok!

**Pull request merged**
